name = "scamguardapi"
main = "worker.js"
compatibility_date = "2023-08-23"
preview_urls = false
workers_dev = false
send_metrics = false

[observability]
enabled = false
head_sampling_rate = 0.5

[vars]
REQUIRE_AUTH = "true"

[[kv_namespaces]]
binding = "TOKEN_LIST"
id = "6b2fc82222f24d07b37400a3fd752cab"